default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: devise_token_auth_demo_development

test:
  <<: *default
  database: devise_token_auth_demo_test

production:
  <<: *default
  database: devise_token_auth_demo_production
